-- Collapses media_metadata into media_items.
--
-- Generated by drizzle-kit, then hand-edited: the generated version dropped
-- media_metadata before copying anything out of it, and added the NOT NULL
-- columns with no default (which cannot succeed on a non-empty table). The
-- data copy and the two guards below are hand-written; statement order matters.
--
-- Drizzle wraps this file in a single transaction, so either guard firing
-- aborts the whole migration and leaves the database untouched.

-- Guard 1: abort if any user holds two items against one metadata row. The new
-- unique index could not be created, and silently dropping a row is not an option.
DO $$
DECLARE dupes integer;
BEGIN
	SELECT count(*) INTO dupes FROM (
		SELECT "user_id", "media_item_metadata_id"
		FROM "media_items"
		GROUP BY "user_id", "media_item_metadata_id"
		HAVING count(*) > 1
	) d;
	IF dupes > 0 THEN
		RAISE EXCEPTION
			'0036 aborted: % (user_id, media_item_metadata_id) pairs have multiple media_items rows. Resolve these in the app before migrating.', dupes;
	END IF;
END $$;--> statement-breakpoint

ALTER TABLE "media_items" ADD COLUMN "type" "media_type";--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "title" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "cover_image_url" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "release_date" date;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "external_id" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "external_source" text;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "metadata" jsonb;--> statement-breakpoint

-- Copy each metadata row onto every item that references it. A row shared by two
-- users lands an independent copy on each user's item.
UPDATE "media_items" mi
SET "type" = m."type",
	"title" = m."title",
	"description" = m."description",
	"cover_image_url" = m."cover_image_url",
	"release_date" = m."release_date",
	"external_id" = m."external_id",
	"external_source" = m."external_source",
	"metadata" = m."metadata"
FROM "media_metadata" m
WHERE m."id" = mi."media_item_metadata_id";--> statement-breakpoint

-- Guard 2: every item must have received values. A NULL title here means an item
-- referenced a metadata row that does not exist — abort rather than lose it.
DO $$
DECLARE orphans integer;
BEGIN
	SELECT count(*) INTO orphans FROM "media_items" WHERE "title" IS NULL;
	IF orphans > 0 THEN
		RAISE EXCEPTION
			'0036 aborted: % media_items rows received no metadata (dangling media_item_metadata_id).', orphans;
	END IF;
END $$;--> statement-breakpoint

ALTER TABLE "media_items" ALTER COLUMN "type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "media_items" ALTER COLUMN "title" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "media_items" ALTER COLUMN "external_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "media_items" ALTER COLUMN "external_source" SET NOT NULL;--> statement-breakpoint

-- Generated columns are added after the copy so they compute from real values.
ALTER TABLE "media_items" ADD COLUMN "sort_title" text GENERATED ALWAYS AS (CASE
				WHEN LOWER(title) LIKE 'the %' THEN SUBSTRING(title FROM 5)
				WHEN LOWER(title) LIKE 'an %' THEN SUBSTRING(title FROM 4)
				WHEN LOWER(title) LIKE 'a %' THEN SUBSTRING(title FROM 3)
				ELSE title
			END) STORED;--> statement-breakpoint
ALTER TABLE "media_items" ADD COLUMN "series_sort_name" text GENERATED ALWAYS AS (CASE
				WHEN LOWER(metadata->>'series') LIKE 'the %' THEN SUBSTRING(metadata->>'series' FROM 5)
				WHEN LOWER(metadata->>'series') LIKE 'an %' THEN SUBSTRING(metadata->>'series' FROM 4)
				WHEN LOWER(metadata->>'series') LIKE 'a %' THEN SUBSTRING(metadata->>'series' FROM 3)
				ELSE metadata->>'series'
			END) STORED;--> statement-breakpoint

CREATE UNIQUE INDEX "media_items_user_external_unique" ON "media_items" USING btree ("user_id","external_id","external_source");--> statement-breakpoint

-- Dropping the column also drops media_items_media_item_metadata_id_media_metadata_id_fk.
ALTER TABLE "media_items" DROP COLUMN "media_item_metadata_id";--> statement-breakpoint

-- Orphan metadata rows (referenced by no item) go with the table. They are
-- unreachable by any user, so there is nothing to preserve.
DROP TABLE "media_metadata";
