/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSeriesSeriesIdRouteImport } from './routes/_authenticated/series.$seriesId'
import { Route as AuthenticatedMediaItemDetailsMediaItemIdRouteImport } from './routes/_authenticated/mediaItemDetails.$mediaItemId'
import { Route as AuthenticatedGenreGenreIdRouteImport } from './routes/_authenticated/genre.$genreId'
import { Route as AuthenticatedCreatorCreatorIdRouteImport } from './routes/_authenticated/creator.$creatorId'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppSeriesRouteImport } from './routes/_authenticated/_app/series'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/_app/library'
import { Route as AuthenticatedReportsReportIdDrilldownRouteImport } from './routes/_authenticated/reports.$reportId.drilldown'
import { Route as AuthenticatedAppViewsViewIdRouteImport } from './routes/_authenticated/_app/views.$viewId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeriesSeriesIdRoute =
  AuthenticatedSeriesSeriesIdRouteImport.update({
    id: '/series/$seriesId',
    path: '/series/$seriesId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMediaItemDetailsMediaItemIdRoute =
  AuthenticatedMediaItemDetailsMediaItemIdRouteImport.update({
    id: '/mediaItemDetails/$mediaItemId',
    path: '/mediaItemDetails/$mediaItemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGenreGenreIdRoute =
  AuthenticatedGenreGenreIdRouteImport.update({
    id: '/genre/$genreId',
    path: '/genre/$genreId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreatorCreatorIdRoute =
  AuthenticatedCreatorCreatorIdRouteImport.update({
    id: '/creator/$creatorId',
    path: '/creator/$creatorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeriesRoute = AuthenticatedAppSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedReportsReportIdDrilldownRoute =
  AuthenticatedReportsReportIdDrilldownRouteImport.update({
    id: '/reports/$reportId/drilldown',
    path: '/reports/$reportId/drilldown',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppViewsViewIdRoute =
  AuthenticatedAppViewsViewIdRouteImport.update({
    id: '/views/$viewId',
    path: '/views/$viewId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/series': typeof AuthenticatedAppSeriesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/creator/$creatorId': typeof AuthenticatedCreatorCreatorIdRoute
  '/genre/$genreId': typeof AuthenticatedGenreGenreIdRoute
  '/mediaItemDetails/$mediaItemId': typeof AuthenticatedMediaItemDetailsMediaItemIdRoute
  '/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/views/$viewId': typeof AuthenticatedAppViewsViewIdRoute
  '/reports/$reportId/drilldown': typeof AuthenticatedReportsReportIdDrilldownRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/series': typeof AuthenticatedAppSeriesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/creator/$creatorId': typeof AuthenticatedCreatorCreatorIdRoute
  '/genre/$genreId': typeof AuthenticatedGenreGenreIdRoute
  '/mediaItemDetails/$mediaItemId': typeof AuthenticatedMediaItemDetailsMediaItemIdRoute
  '/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/views/$viewId': typeof AuthenticatedAppViewsViewIdRoute
  '/reports/$reportId/drilldown': typeof AuthenticatedReportsReportIdDrilldownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/_app/series': typeof AuthenticatedAppSeriesRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/creator/$creatorId': typeof AuthenticatedCreatorCreatorIdRoute
  '/_authenticated/genre/$genreId': typeof AuthenticatedGenreGenreIdRoute
  '/_authenticated/mediaItemDetails/$mediaItemId': typeof AuthenticatedMediaItemDetailsMediaItemIdRoute
  '/_authenticated/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/views/$viewId': typeof AuthenticatedAppViewsViewIdRoute
  '/_authenticated/reports/$reportId/drilldown': typeof AuthenticatedReportsReportIdDrilldownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/library'
    | '/series'
    | '/settings'
    | '/creator/$creatorId'
    | '/genre/$genreId'
    | '/mediaItemDetails/$mediaItemId'
    | '/series/$seriesId'
    | '/api/auth/$'
    | '/views/$viewId'
    | '/reports/$reportId/drilldown'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/library'
    | '/series'
    | '/settings'
    | '/creator/$creatorId'
    | '/genre/$genreId'
    | '/mediaItemDetails/$mediaItemId'
    | '/series/$seriesId'
    | '/api/auth/$'
    | '/views/$viewId'
    | '/reports/$reportId/drilldown'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/_app/library'
    | '/_authenticated/_app/series'
    | '/_authenticated/_app/settings'
    | '/_authenticated/creator/$creatorId'
    | '/_authenticated/genre/$genreId'
    | '/_authenticated/mediaItemDetails/$mediaItemId'
    | '/_authenticated/series/$seriesId'
    | '/api/auth/$'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/views/$viewId'
    | '/_authenticated/reports/$reportId/drilldown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/series/$seriesId': {
      id: '/_authenticated/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AuthenticatedSeriesSeriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mediaItemDetails/$mediaItemId': {
      id: '/_authenticated/mediaItemDetails/$mediaItemId'
      path: '/mediaItemDetails/$mediaItemId'
      fullPath: '/mediaItemDetails/$mediaItemId'
      preLoaderRoute: typeof AuthenticatedMediaItemDetailsMediaItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/genre/$genreId': {
      id: '/_authenticated/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof AuthenticatedGenreGenreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creator/$creatorId': {
      id: '/_authenticated/creator/$creatorId'
      path: '/creator/$creatorId'
      fullPath: '/creator/$creatorId'
      preLoaderRoute: typeof AuthenticatedCreatorCreatorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/series': {
      id: '/_authenticated/_app/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedAppSeriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/library': {
      id: '/_authenticated/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/reports/$reportId/drilldown': {
      id: '/_authenticated/reports/$reportId/drilldown'
      path: '/reports/$reportId/drilldown'
      fullPath: '/reports/$reportId/drilldown'
      preLoaderRoute: typeof AuthenticatedReportsReportIdDrilldownRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/views/$viewId': {
      id: '/_authenticated/_app/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/views/$viewId'
      preLoaderRoute: typeof AuthenticatedAppViewsViewIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppSeriesRoute: typeof AuthenticatedAppSeriesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppViewsViewIdRoute: typeof AuthenticatedAppViewsViewIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppSeriesRoute: AuthenticatedAppSeriesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppViewsViewIdRoute: AuthenticatedAppViewsViewIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedCreatorCreatorIdRoute: typeof AuthenticatedCreatorCreatorIdRoute
  AuthenticatedGenreGenreIdRoute: typeof AuthenticatedGenreGenreIdRoute
  AuthenticatedMediaItemDetailsMediaItemIdRoute: typeof AuthenticatedMediaItemDetailsMediaItemIdRoute
  AuthenticatedSeriesSeriesIdRoute: typeof AuthenticatedSeriesSeriesIdRoute
  AuthenticatedReportsReportIdDrilldownRoute: typeof AuthenticatedReportsReportIdDrilldownRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedCreatorCreatorIdRoute: AuthenticatedCreatorCreatorIdRoute,
  AuthenticatedGenreGenreIdRoute: AuthenticatedGenreGenreIdRoute,
  AuthenticatedMediaItemDetailsMediaItemIdRoute:
    AuthenticatedMediaItemDetailsMediaItemIdRoute,
  AuthenticatedSeriesSeriesIdRoute: AuthenticatedSeriesSeriesIdRoute,
  AuthenticatedReportsReportIdDrilldownRoute:
    AuthenticatedReportsReportIdDrilldownRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
