/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedDetailsRouteImport } from './routes/_authenticated/_details'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppSeriesRouteImport } from './routes/_authenticated/_app/series'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/_app/library'
import { Route as AuthenticatedDetailsSeriesSeriesIdRouteImport } from './routes/_authenticated/_details/series.$seriesId'
import { Route as AuthenticatedDetailsMediaItemDetailsMediaItemIdRouteImport } from './routes/_authenticated/_details/mediaItemDetails.$mediaItemId'
import { Route as AuthenticatedDetailsGenreGenreIdRouteImport } from './routes/_authenticated/_details/genre.$genreId'
import { Route as AuthenticatedDetailsCreatorCreatorIdRouteImport } from './routes/_authenticated/_details/creator.$creatorId'
import { Route as AuthenticatedAppViewsViewIdRouteImport } from './routes/_authenticated/_app/views.$viewId'
import { Route as AuthenticatedDetailsReportsReportIdDrilldownRouteImport } from './routes/_authenticated/_details/reports.$reportId.drilldown'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDetailsRoute = AuthenticatedDetailsRouteImport.update({
  id: '/_details',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeriesRoute = AuthenticatedAppSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedDetailsSeriesSeriesIdRoute =
  AuthenticatedDetailsSeriesSeriesIdRouteImport.update({
    id: '/series/$seriesId',
    path: '/series/$seriesId',
    getParentRoute: () => AuthenticatedDetailsRoute,
  } as any)
const AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute =
  AuthenticatedDetailsMediaItemDetailsMediaItemIdRouteImport.update({
    id: '/mediaItemDetails/$mediaItemId',
    path: '/mediaItemDetails/$mediaItemId',
    getParentRoute: () => AuthenticatedDetailsRoute,
  } as any)
const AuthenticatedDetailsGenreGenreIdRoute =
  AuthenticatedDetailsGenreGenreIdRouteImport.update({
    id: '/genre/$genreId',
    path: '/genre/$genreId',
    getParentRoute: () => AuthenticatedDetailsRoute,
  } as any)
const AuthenticatedDetailsCreatorCreatorIdRoute =
  AuthenticatedDetailsCreatorCreatorIdRouteImport.update({
    id: '/creator/$creatorId',
    path: '/creator/$creatorId',
    getParentRoute: () => AuthenticatedDetailsRoute,
  } as any)
const AuthenticatedAppViewsViewIdRoute =
  AuthenticatedAppViewsViewIdRouteImport.update({
    id: '/views/$viewId',
    path: '/views/$viewId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedDetailsReportsReportIdDrilldownRoute =
  AuthenticatedDetailsReportsReportIdDrilldownRouteImport.update({
    id: '/reports/$reportId/drilldown',
    path: '/reports/$reportId/drilldown',
    getParentRoute: () => AuthenticatedDetailsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/series': typeof AuthenticatedAppSeriesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/views/$viewId': typeof AuthenticatedAppViewsViewIdRoute
  '/creator/$creatorId': typeof AuthenticatedDetailsCreatorCreatorIdRoute
  '/genre/$genreId': typeof AuthenticatedDetailsGenreGenreIdRoute
  '/mediaItemDetails/$mediaItemId': typeof AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute
  '/series/$seriesId': typeof AuthenticatedDetailsSeriesSeriesIdRoute
  '/reports/$reportId/drilldown': typeof AuthenticatedDetailsReportsReportIdDrilldownRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/library': typeof AuthenticatedAppLibraryRoute
  '/series': typeof AuthenticatedAppSeriesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/views/$viewId': typeof AuthenticatedAppViewsViewIdRoute
  '/creator/$creatorId': typeof AuthenticatedDetailsCreatorCreatorIdRoute
  '/genre/$genreId': typeof AuthenticatedDetailsGenreGenreIdRoute
  '/mediaItemDetails/$mediaItemId': typeof AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute
  '/series/$seriesId': typeof AuthenticatedDetailsSeriesSeriesIdRoute
  '/reports/$reportId/drilldown': typeof AuthenticatedDetailsReportsReportIdDrilldownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_details': typeof AuthenticatedDetailsRouteWithChildren
  '/_authenticated/_app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/_app/series': typeof AuthenticatedAppSeriesRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/views/$viewId': typeof AuthenticatedAppViewsViewIdRoute
  '/_authenticated/_details/creator/$creatorId': typeof AuthenticatedDetailsCreatorCreatorIdRoute
  '/_authenticated/_details/genre/$genreId': typeof AuthenticatedDetailsGenreGenreIdRoute
  '/_authenticated/_details/mediaItemDetails/$mediaItemId': typeof AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute
  '/_authenticated/_details/series/$seriesId': typeof AuthenticatedDetailsSeriesSeriesIdRoute
  '/_authenticated/_details/reports/$reportId/drilldown': typeof AuthenticatedDetailsReportsReportIdDrilldownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/library'
    | '/series'
    | '/settings'
    | '/api/auth/$'
    | '/views/$viewId'
    | '/creator/$creatorId'
    | '/genre/$genreId'
    | '/mediaItemDetails/$mediaItemId'
    | '/series/$seriesId'
    | '/reports/$reportId/drilldown'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/library'
    | '/series'
    | '/settings'
    | '/api/auth/$'
    | '/views/$viewId'
    | '/creator/$creatorId'
    | '/genre/$genreId'
    | '/mediaItemDetails/$mediaItemId'
    | '/series/$seriesId'
    | '/reports/$reportId/drilldown'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/_details'
    | '/_authenticated/_app/library'
    | '/_authenticated/_app/series'
    | '/_authenticated/_app/settings'
    | '/api/auth/$'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/views/$viewId'
    | '/_authenticated/_details/creator/$creatorId'
    | '/_authenticated/_details/genre/$genreId'
    | '/_authenticated/_details/mediaItemDetails/$mediaItemId'
    | '/_authenticated/_details/series/$seriesId'
    | '/_authenticated/_details/reports/$reportId/drilldown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_details': {
      id: '/_authenticated/_details'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDetailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/series': {
      id: '/_authenticated/_app/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedAppSeriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/library': {
      id: '/_authenticated/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_details/series/$seriesId': {
      id: '/_authenticated/_details/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AuthenticatedDetailsSeriesSeriesIdRouteImport
      parentRoute: typeof AuthenticatedDetailsRoute
    }
    '/_authenticated/_details/mediaItemDetails/$mediaItemId': {
      id: '/_authenticated/_details/mediaItemDetails/$mediaItemId'
      path: '/mediaItemDetails/$mediaItemId'
      fullPath: '/mediaItemDetails/$mediaItemId'
      preLoaderRoute: typeof AuthenticatedDetailsMediaItemDetailsMediaItemIdRouteImport
      parentRoute: typeof AuthenticatedDetailsRoute
    }
    '/_authenticated/_details/genre/$genreId': {
      id: '/_authenticated/_details/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof AuthenticatedDetailsGenreGenreIdRouteImport
      parentRoute: typeof AuthenticatedDetailsRoute
    }
    '/_authenticated/_details/creator/$creatorId': {
      id: '/_authenticated/_details/creator/$creatorId'
      path: '/creator/$creatorId'
      fullPath: '/creator/$creatorId'
      preLoaderRoute: typeof AuthenticatedDetailsCreatorCreatorIdRouteImport
      parentRoute: typeof AuthenticatedDetailsRoute
    }
    '/_authenticated/_app/views/$viewId': {
      id: '/_authenticated/_app/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/views/$viewId'
      preLoaderRoute: typeof AuthenticatedAppViewsViewIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_details/reports/$reportId/drilldown': {
      id: '/_authenticated/_details/reports/$reportId/drilldown'
      path: '/reports/$reportId/drilldown'
      fullPath: '/reports/$reportId/drilldown'
      preLoaderRoute: typeof AuthenticatedDetailsReportsReportIdDrilldownRouteImport
      parentRoute: typeof AuthenticatedDetailsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppSeriesRoute: typeof AuthenticatedAppSeriesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppViewsViewIdRoute: typeof AuthenticatedAppViewsViewIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppSeriesRoute: AuthenticatedAppSeriesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppViewsViewIdRoute: AuthenticatedAppViewsViewIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedDetailsRouteChildren {
  AuthenticatedDetailsCreatorCreatorIdRoute: typeof AuthenticatedDetailsCreatorCreatorIdRoute
  AuthenticatedDetailsGenreGenreIdRoute: typeof AuthenticatedDetailsGenreGenreIdRoute
  AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute: typeof AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute
  AuthenticatedDetailsSeriesSeriesIdRoute: typeof AuthenticatedDetailsSeriesSeriesIdRoute
  AuthenticatedDetailsReportsReportIdDrilldownRoute: typeof AuthenticatedDetailsReportsReportIdDrilldownRoute
}

const AuthenticatedDetailsRouteChildren: AuthenticatedDetailsRouteChildren = {
  AuthenticatedDetailsCreatorCreatorIdRoute:
    AuthenticatedDetailsCreatorCreatorIdRoute,
  AuthenticatedDetailsGenreGenreIdRoute: AuthenticatedDetailsGenreGenreIdRoute,
  AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute:
    AuthenticatedDetailsMediaItemDetailsMediaItemIdRoute,
  AuthenticatedDetailsSeriesSeriesIdRoute:
    AuthenticatedDetailsSeriesSeriesIdRoute,
  AuthenticatedDetailsReportsReportIdDrilldownRoute:
    AuthenticatedDetailsReportsReportIdDrilldownRoute,
}

const AuthenticatedDetailsRouteWithChildren =
  AuthenticatedDetailsRoute._addFileChildren(AuthenticatedDetailsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDetailsRoute: typeof AuthenticatedDetailsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDetailsRoute: AuthenticatedDetailsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
